# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "CV"
  url = "/authors/mubashir-ali/"
  weight = 25

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 40

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
